#!/bin/zsh

#Script to install all dependencies

mkdir /Script
touch /scriptfile.txt
echo "Testing Script File" >> /scriptfile.txt

plugins=
#Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

#Download and Install Node JS

#Install Salesforce CLI
npm install sfdx-cli --global

#Verify Salesforce CLI Version
sfdx --version

#Verify the Salesforce CLI plug-in version
sfdx plugins --core

#Install GitHub CLI

#Install Maven

#brew doctor - 'Warning: <path> was not tapped properly! run...
